services:
  migrate:
    volumes:
      - ./app:/workspace/app
      - ./packages:/workspace/packages:ro
      - app-node-modules:/workspace/app/node_modules

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
      target: dependencies
    command: ["yarn", "dev", "--host", "0.0.0.0"]
    environment:
      NODE_ENV: development
    volumes:
      - ./app:/workspace/app
      - ./packages:/workspace/packages:ro
      - app-node-modules:/workspace/app/node_modules

  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
      target: dependencies
    command: ["yarn", "dev"]
    volumes:
      - ./docs:/workspace/docs
      - ./packages:/workspace/packages:ro
      - docs-node-modules:/workspace/docs/node_modules

volumes:
  app-node-modules:
  docs-node-modules:
