server {
  listen 3001;
  server_name _;
  root /usr/share/nginx/html;

  location /docs/assets/ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location /docs/ {
    try_files $uri $uri.html $uri/ =404;
  }
}
